stages:
  - test

test:
  stage: test
  image: python:3.6
  script:
  - apt-get update -qy
  - pip install -r requirements.txt
  - pip install coverage
  - python -m coverage run test_update_metadata_curl_files.py
  - python -m coverage report -m
  coverage: '/(\d+%)$/'