stages:
  - test

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y python python-pip
  - pip install -r requirements.txt
  - pip install coverage
  - python -m coverage run test_update_metadata_curl_files.py

coverage:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y python python-pip
  - pip install -r requirements.txt
  - pip install coverage
  - python -m coverage html
  coverage: '/(\d+%)$/'